/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.braully.bds.desktop;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.sql.DataSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.Banner;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 *
 * @author braully
 */
@SpringBootApplication
public class AplicacaoDesktop extends javax.swing.JFrame implements CommandLineRunner {

    /**
     * Creates new form Teste4
     */
    public AplicacaoDesktop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        conteudo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arvoreMenu = new javax.swing.JTree();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        conteudo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        conteudo.setMinimumSize(new java.awt.Dimension(300, 300));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Banco de Dados");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Empresa");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Funcionário");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Busca Funcionário");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Departamento");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        arvoreMenu.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        arvoreMenu.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                arvoreMenuValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(arvoreMenu);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conteudo, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(conteudo, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arvoreMenuValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_arvoreMenuValueChanged
        // TODO add your handling code here:
        conteudo.removeAll();
        Object selecionado = evt.getNewLeadSelectionPath().getLastPathComponent().toString();
        if ("Funcionário".equals(selecionado)) {
            PanelFuncionario panel = new PanelFuncionario();
            conteudo.add(panel);
        } else if ("Busca Funcionário".equals(selecionado)) {
            PanelFuncionariosLista panel = new PanelFuncionariosLista();
            conteudo.add(panel);
        } else if ("Departamento".equals(selecionado)) {
            PanelDepartamento panel = new PanelDepartamento();
            conteudo.add(panel);
            panel.carregarTodosDepartamentos();
            panel.carregarComboGerente();
        }
        validate();
        repaint();
    }//GEN-LAST:event_arvoreMenuValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplicacaoDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplicacaoDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplicacaoDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplicacaoDesktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        SpringApplication app = new SpringApplication(AplicacaoDesktop.class);
        app.setHeadless(false);
        app.setBannerMode(Banner.Mode.OFF);
        app.run(args);

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arvoreMenu;
    private javax.swing.JPanel conteudo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run(String... args) throws Exception {
        System.out.println("DATASOURCE = " + dataSource);
        this.setVisible(true);
    }

    public void salvarFuncionario(String nome, String cpf) throws SQLException {
        Statement statement = dataSource.getConnection().createStatement();
        String comandoSql = "insert into FUNCIONARIO (pnome, cpf) VALUES ('" + nome + "', '" + cpf + "');";
        statement.execute(comandoSql);
        statement.close();
        System.out.println("Comando sql excutado: " + comandoSql);
    }

    public List buscarFuncionario(String nome) throws SQLException {
        Statement statement = dataSource.getConnection().createStatement();
        ResultSet resultado = statement.executeQuery("select pnome, cpf from funcionario where pnome like '%" + nome + "%'");

        List listaResultado = new ArrayList();
        while (resultado.next()) {
            //Recupera valor referente ao nome da coluna
            listaResultado.add(new String[]{resultado.getString("pnome"), resultado.getString("cpf")});
        }

        resultado.close();
        statement.close();

        return listaResultado;
    }

    @Autowired(required = false)
    DataSource dataSource;

    void deletarFuncionario(String cpfFuncionario) throws SQLException {
        Statement statement = dataSource.getConnection().createStatement();
        String comandoSql = "DELETE FROM FUNCIONARIO WHERE cpf='" + cpfFuncionario + "';";
        statement.execute(comandoSql);
        statement.close();
        System.out.println("Comando sql excutado: " + comandoSql);
    }

    List buscaTodosDepartamentos() throws SQLException {
        Statement statement = dataSource.getConnection().createStatement();
        ResultSet resultado = statement.executeQuery("SELECT dnumero, dnome, COUNT(cpf) "
                + "FROM Departamento LEFT JOIN Funcionario ON dnr = dnumero "
                + "GROUP BY dnumero, dnome");

        List listaResultado = new ArrayList();
        while (resultado.next()) {
            //Recupera valor referente ao nome da coluna
            listaResultado.add(new String[]{resultado.getString("dnumero"),
                resultado.getString("dnome"), resultado.getString("count")});
        }

        resultado.close();
        statement.close();
        return listaResultado;
    }
}
